### ISSUE TITLE
remote_ssp_dump.py and loader.bin

### ISSUE THREAD

**Issue by soufianetahiri** [icyguider/MoreImpacketExamples#1]
Hello,
not sure if It's an issue or if I missed something 

![image](https://user-images.githubusercontent.com/17729335/200294863-4bfe812f-1a26-4874-996a-c4fa17914e16.png)

Do I need to have donut installed ?

**Comment by icyguider** [comment]
I'd really recommend understanding what exactly the script does before trying to use it. That's kind of the whole point of this project...

**Comment by soufianetahiri** [comment]
👏
